import Head from 'next/head';
import { useSession, signIn, signOut } from 'next-auth/react';
import {
  Heading,
  Flex,
  Spacer,
  Button,
  Menu,
  MenuButton,
  MenuList,
  MenuItem,
  Avatar,
  Text,
  MenuDivider,
  Card,
  CardBody,
  Stack,
  IconButton,
  Image,
  Icon,
} from '@chakra-ui/react';
import { FiShare } from 'react-icons/fi';

export default function Home() {
  const { data: session, status } = useSession();

  return (
    <>
      <Head>
        <title>Tonz</title>
      </Head>
      <nav>
        <Flex w="100%" p={4} justify="evenly">
          <Heading size="md">Tonz</Heading>
          <Spacer />
          {status == 'unauthenticated' || status == 'loading' ? (
            <Button onClick={() => signIn()}>Login</Button>
          ) : (
            <Menu>
              <MenuButton>
                <Avatar
                  name={session!.user?.name || ''}
                  src={session!.user?.picture || ''}
                  size={'sm'}
                />
              </MenuButton>
              <MenuList>
                <Text px={3}>{session!.user?.name}</Text>
                <MenuDivider />
                <MenuItem>Connect Account</MenuItem>
                <MenuItem>Generate Recommendations</MenuItem>
                <MenuItem onClick={() => signOut()}>Log Out</MenuItem>
              </MenuList>
            </Menu>
          )}
        </Flex>
      </nav>
      <div>
        {session ? (
          <>
            <Card maxW="sm" m="auto">
              <CardBody>
                <Heading size="md" mb="4">
                  Listening To
                </Heading>
                <Image
                  src="https://c.neevacdn.net/image/fetch/s--35cyv_xI--/https%3A//m.media-amazon.com/images/I/7176iTv3geL._SS500_.jpg?savepath=7176iTv3geL._SS500_.jpg"
                  alt="Album Cover"
                  borderRadius="lg"
                />
                <Stack mt="6" mb={1} spacing="3">
                  <Heading size="md">Never Gonna Give You Up</Heading>
                  <Text>Rick Astley - Whenever You Need Somebody</Text>
                </Stack>
                <IconButton
                  h="auto"
                  minW={0}
                  p={1}
                  aria-label="Share with friends"
                  icon={<Icon p={0} as={FiShare} />}
                  colorScheme="blue"
                  variant="ghost"
                />
              </CardBody>
            </Card>
          </>
        ) : (
          <Heading textAlign="center">What is Tonz?</Heading>
        )}
      </div>
    </>
  );
}

// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main className={styles.main}>
//         <div className={styles.description}>
//           <p>Tonz</p>
//           <div>
//             <Link href="/login" target="_blank" rel="noopener noreferrer">
//               Login
//             </Link>
//           </div>
//         </div>

//         <div className={styles.center}>
//           {/* <Image
//             className={styles.logo}
//             src="/next.svg"
//             alt="Next.js Logo"
//             width={180}
//             height={37}
//             priority
//           /> */}
//           <div className={styles.thirteen}>
//             Tonz: The Music Social Hub
//             {/* <Image
//               src="/thirteen.svg"
//               alt="13"
//               width={40}
//               height={31}
//               priority
//             /> */}
//           </div>
//         </div>

//         <div className={styles.grid}>
//           <a
//             href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Docs <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Find in-depth information about Next.js features and&nbsp;API.
//             </p>
//           </a>

//           <a
//             href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Learn <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Learn about Next.js in an interactive course with&nbsp;quizzes!
//             </p>
//           </a>

//           <a
//             href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Templates <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Discover and deploy boilerplate example Next.js&nbsp;projects.
//             </p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Deploy <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Instantly deploy your Next.js site to a shareable URL
//               with&nbsp;Vercel.
//             </p>
//           </a>
//         </div>
//       </main>
//     </>
//   );
// }
