import Head from "next/head";
import Image from "next/image";
import NextLink from "next/link";
import { useSession, signIn, signOut } from "next-auth/react";
import {
  Heading,
  Flex,
  Spacer,
  Link,
  Button,
  Menu,
  MenuButton,
  MenuList,
  MenuItem,
  Avatar,
} from "@chakra-ui/react";

export default function Home() {
  const { data: session } = useSession();
  return (
    <>
      <Head>
        <title>Tonz</title>
      </Head>
      <nav>
        <Flex w="100%" p={4} justify="evenly">
          <Heading>Tonz</Heading>
          <Spacer />
          {!session ? (
            <Button onClick={signIn}>Login</Button>
          ) : (
            <Menu>
              <MenuButton>
                <Avatar
                  name={session.user.name}
                  src={session.user.image}
                  as={Avatar}
                />
                <Heading>{session.user.email}</Heading>
              </MenuButton>
              <MenuList>
                <MenuItem>Connect Account</MenuItem>
                <MenuItem>Generate Recommendations</MenuItem>
                <MenuItem>Log Out</MenuItem>
              </MenuList>
            </Menu>
          )}
        </Flex>
      </nav>
    </>
  );
}

// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main className={styles.main}>
//         <div className={styles.description}>
//           <p>Tonz</p>
//           <div>
//             <Link href="/login" target="_blank" rel="noopener noreferrer">
//               Login
//             </Link>
//           </div>
//         </div>

//         <div className={styles.center}>
//           {/* <Image
//             className={styles.logo}
//             src="/next.svg"
//             alt="Next.js Logo"
//             width={180}
//             height={37}
//             priority
//           /> */}
//           <div className={styles.thirteen}>
//             Tonz: The Music Social Hub
//             {/* <Image
//               src="/thirteen.svg"
//               alt="13"
//               width={40}
//               height={31}
//               priority
//             /> */}
//           </div>
//         </div>

//         <div className={styles.grid}>
//           <a
//             href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Docs <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Find in-depth information about Next.js features and&nbsp;API.
//             </p>
//           </a>

//           <a
//             href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Learn <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Learn about Next.js in an interactive course with&nbsp;quizzes!
//             </p>
//           </a>

//           <a
//             href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Templates <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Discover and deploy boilerplate example Next.js&nbsp;projects.
//             </p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2 className={inter.className}>
//               Deploy <span>-&gt;</span>
//             </h2>
//             <p className={inter.className}>
//               Instantly deploy your Next.js site to a shareable URL
//               with&nbsp;Vercel.
//             </p>
//           </a>
//         </div>
//       </main>
//     </>
//   );
// }
